version: "3"

networks:
  traefik_webgateway:
    external: true

services:
  infoportal:
    build: .
    container_name: infoportal
    restart: always
    networks:
      - traefik_webgateway
    #volumes:
    #  - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.provider.docker.network=traefik_webgateway"
      - "traefik.http.routers.infoportal.entrypoints=websecure"
      - "traefik.http.routers.infoportal.rule=Host(`werkd.saw-leipzig.de`)"
      - "traefik.http.routers.infoportal.tls=true"
